version: "3.9"

services:

    git_backup:
        image: "chrisbesch/docker_git_backup"

        volumes:
            - "./repo:/var/lib/git_backup/repo"
            - "./temp:/origin"
            - "./other_repos.conf:/var/lib/git_backup/other_repos.conf:ro"
        
        environment:
            # optional
            # - GITHUB_USERNAME=
            # - GITHUB_PASSWORD=
            - BORG_COMPRESSION=zstd,22
            - "PRUNE_CFG=--keep-last 1 --keep-daily 4 --keep-monthly 3 --keep-yearly 1"
            - "CRON_TIME=* * * * *"
            - TZ=Europe/Berlin

        restart: "always"

    docker_cron:
        image: "chrisbesch/docker_cron"

        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin

        restart: "always"

